import Head from "next/head";
import { Inter } from "next/font/google";
import FileUploadForm from "@/components/FileUpload";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-auto max-w-7xl sm:px-6 lg:px-8">
          <div className="divide-y divide-gray-200 overflow-hidden rounded-lg bg-white shadow">
            <div className="px-4 py-5 sm:px-6">
              <h3 className="text-lg leading-6 font-medium text-gray-900">
                Upload a PDF
              </h3>
            </div>
            <div className="px-4 py-5 sm:p-6">
              <FileUploadForm />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
